import { IQuestion } from '@interfaces/common';

export const SECTION_B3_QUESTIONS: IQuestion[] = [
  {
    questionId: 'B1',
    question: 'Name of Respondent',
    answer: '',
    questionType: 'text',
    maxLength: 100,
  },
  {
    questionId: 'B2',
    question: 'CNIC #',
    answer: '',
    questionType: 'text',
    maxLength: 15,
  },
  {
    questionId: 'B3',
    question: 'Contact No.',
    answer: '',
    questionType: 'text',
    keyboardType: 'phone-pad',
    maxLength: 15,
  },
  {
    questionId: 'B5',
    question: 'Taluka',
    answer: '',
    questionType: 'text',
    maxLength: 50,
  },
  {
    questionId: 'B4',
    question: 'Name of Village/Goth',
    answer: '',
    questionType: 'text',
    maxLength: 100,
  },
  {
    questionId: 'B6',
    question: 'District',
    answer: '',
    questionType: 'text',
    maxLength: 50,
  },
  {
    questionId: 'B7',
    question: 'Gender',
    options: ['Male', 'Female'],
    answer: '',
    questionType: 'radio',
  },
  {
    questionId: 'B8',
    question: 'Status of House',
    options: ['Own', 'Rented', 'Other (Specify)'],
    answer: '',
    questionType: 'radio',
  },
  {
    questionId: 'B8a',
    question: 'If you selected "Other", please specify',
    answer: '',
    questionType: 'text',
    maxLength: 100,
  },
  {
    questionId: 'B9',
    question: 'Number of HH members currently earning',
    answer: '',
    questionType: 'number',
    keyboardType: 'numeric',
    maxLength: 2,
  },
  {
    questionId: 'B9a',
    question: 'Number of male HH members currently earning',
    answer: '',
    questionType: 'number',
    keyboardType: 'numeric',
    maxLength: 2,
  },
  {
    questionId: 'B9b',
    question: 'Number of female HH members currently earning',
    answer: '',
    questionType: 'number',
    keyboardType: 'numeric',
    maxLength: 2,
  },
  {
    questionId: 'B10',
    question: 'Source of Income of the HH',
    options: [
      'Farming',
      'Govt Service',
      'Private Job',
      'Own Business',
      'Daily Wages',
      'Artisan',
      'Other',
    ],
    answer: '',
    questionType: 'checkbox',
  },
  {
    questionId: 'B10a',
    question: 'If you selected "Other", please specify',
    answer: '',
    questionType: 'text',
    maxLength: 100,
  },
  {
    questionId: 'B11',
    question: 'Total Monthly Income (PKR)',
    options: [
      '10,000 – 20,000',
      '20,000 - 30,000',
      '30,000 – 40,000',
      '40,000 – 50,000',
      'Other',
    ],
    answer: '',
    questionType: 'radio',
  },
  {
    questionId: 'B11a',
    question: 'If you selected "Other", please specify',
    answer: '',
    questionType: 'text',
    maxLength: 100,
  },
];

export const SECTION_C3_QUESTIONS: IQuestion[] = [
  {
    questionId: 'C1',
    question: 'Do you think KG is effective for women empowerment?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'C2',
    question:
      'Were the KG activities carried out according to the specified design and plans?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Partially'],
  },
  {
    questionId: 'C3',
    question:
      'Have you observed any improvements in household income through KG?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'C4',
    question:
      'Have you observed any improvements for obtaining fresh and hygienic vegetables from your KG?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'C5',
    question: 'Has KG improved your access to vegetables?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'C6',
    question: 'Has KG improved your vegetable consumption?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'D1',
    question: 'Do you believe that KG helps improve water productivity?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'D2',
    question:
      'Do you think your time spent on KG is justified in terms of its return?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Don’t know'],
  },
  {
    questionId: 'D3',
    question: 'Does KG contribute to your skill development?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Don’t know'],
  },
  {
    questionId: 'D4',
    question: 'Does KG enhance your ability to solve financial problems?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Don’t know'],
  },
  {
    questionId: 'D5',
    question: 'Do you think your time has been efficiently utilized?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Don’t know'],
  },
  {
    questionId: 'E1',
    question: 'Do you think KG is the need of rural women/landless poor?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Partially'],
  },
  {
    questionId: 'E3',
    question: 'Do you think KG has minimized labor cost for watering?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Partially'],
  },
  {
    questionId: 'E4',
    question: 'Do you think KG has helped improve vegetable supplies?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Partially'],
  },
  {
    questionId: 'F1',
    question: 'How would you rate the durability of the KG unit?',
    answer: '',
    questionType: 'radio',
    options: ['Good', 'Average', 'Poor'],
  },
  {
    questionId: 'F2',
    question: 'Do you think the KG is sustainable for a longer period?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'F3',
    question: 'Do you think KG has positive effects on the environment?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'F4',
    question: 'Do you think operating KG is farmer-friendly?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'F5',
    question: 'Are you planning to continue KG?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'F6',
    question: 'In your opinion, why do people not go for KG?',
    answer: '',
    questionType: 'checkbox',
    options: [
      'Unawareness',
      'Unavailability of KG kits',
      'Lack of Skill',
      'People don’t have time',
      'Other (Specify)',
    ],
  },
  {
    questionId: 'F7',
    question:
      'What are your major suggestions for the project to improve the quality of support for KG?',
    answer: '',
    questionType: 'text-area',
    maxLength: 1000,
  },
  {
    questionId: 'G1',
    question: 'Is there any contribution of the KG in your household income?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Don’t know'],
  },
];

export const SECTION_D3_QUESTIONS: IQuestion[] = [
  {
    questionId: 'G1',
    question: 'Is there any contribution of the KG in your household income?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Don’t know'],
  },
  {
    questionId: 'G2',
    question:
      'Either in your opinion the neighboring household are motivated to install KG?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'G3',
    question: 'Do you think KG is a good tool for learning?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'G4',
    question:
      'Do you think KG has improved social linkages among landless poor/rural communities?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'G5',
    question: 'Do you think KG has improved the nutritional intake and health?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
  {
    questionId: 'H1',
    question: 'Do you think for installing additional KG in your HH?',
    answer: '',
    questionType: 'radio',
    options: ['Yes', 'No', 'Not Sure'],
  },
];
